#!/usr/bin/env bash
# DrishtiAI Production Installer
# Tested on: Ubuntu 22.04 LTS, Ubuntu 24.04 LTS
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/emanthen/DrishtiAI/master/deploy/install/install.sh | bash
#   -- or --
#   git clone https://github.com/emanthen/DrishtiAI.git && cd DrishtiAI && bash deploy/install/install.sh
#
# What this script does:
#   1. Checks prerequisites (Docker, Compose v2, openssl, Python 3.12+, uv, pnpm)
#   2. Generates all secrets and writes .env (never overwrites an existing .env)
#   3. Generates the RS256 JWT keypair
#   4. Builds Docker images
#   5. Runs Alembic migrations
#   6. Seeds the superadmin account
#   7. Prints a credential summary
#
# After installation start the stack with:
#   docker compose -f deploy/compose/docker-compose.yml up -d

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
COMPOSE="docker compose -f $REPO_ROOT/deploy/compose/docker-compose.yml"

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
ok()   { echo -e "${GREEN}✓${NC} $*"; }
warn() { echo -e "${YELLOW}!${NC} $*"; }
die()  { echo -e "${RED}✗ ERROR:${NC} $*" >&2; exit 1; }
step() { echo -e "\n${CYAN}▶ $*${NC}"; }

# ── 1. Prerequisites ──────────────────────────────────────────────────────────
step "Checking prerequisites"

command -v docker   >/dev/null 2>&1 || die "Docker not found. Install from https://docs.docker.com/engine/install/"
command -v openssl  >/dev/null 2>&1 || die "openssl not found. Run: sudo apt-get install openssl"
command -v python3  >/dev/null 2>&1 || die "python3 not found. Install Python 3.12+."
command -v uv       >/dev/null 2>&1 || die "uv not found. Install from https://docs.astral.sh/uv/"
command -v pnpm     >/dev/null 2>&1 || die "pnpm not found. Run: npm install -g pnpm"

docker compose version >/dev/null 2>&1 || die "Docker Compose v2 not found. Run: sudo apt-get install docker-compose-plugin"

PY_VERSION=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
[[ "$(echo -e "3.12\n$PY_VERSION" | sort -V | head -1)" == "3.12" ]] \
  || die "Python 3.12+ required (found $PY_VERSION)"

ok "All prerequisites met"

# ── 2. Guard against overwriting existing .env ────────────────────────────────
step "Checking for existing .env"

if [[ -f "$ENV_FILE" ]]; then
  warn ".env already exists at $ENV_FILE — skipping secret generation."
  warn "Delete it and re-run if you need to regenerate all secrets."
  SKIP_ENV=1
else
  SKIP_ENV=0
fi

# ── 3. Generate secrets ───────────────────────────────────────────────────────
if [[ "$SKIP_ENV" -eq 0 ]]; then
  step "Generating secrets"

  gen_hex()   { openssl rand -hex "$1"; }
  gen_b64()   { openssl rand -base64 "$1" | tr -d '\n/+=' | head -c "$2"; }
  gen_fernet() {
    python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null \
      || gen_b64 48 44
  }

  POSTGRES_PASSWORD=$(gen_hex 32)
  DJANGO_SECRET_KEY=$(gen_b64 48 50)
  API_SECRET_KEY=$(gen_b64 48 50)
  MINIO_ROOT_PASSWORD=$(gen_hex 32)
  SUPERADMIN_PASSWORD=$(gen_b64 24 20)
  GRAFANA_PASSWORD=$(gen_hex 16)
  GATE_CREDENTIAL_KEY=$(gen_fernet)

  ok "Secrets generated"

  # Generate RS256 JWT keypair
  step "Generating RS256 JWT keypair"
  TMP_PRIV=$(mktemp)
  TMP_PUB=$(mktemp)
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$TMP_PRIV" 2>/dev/null
  openssl rsa -in "$TMP_PRIV" -pubout -out "$TMP_PUB" 2>/dev/null
  # Collapse PEM to single-line with \n literals for .env
  JWT_PRIVATE_KEY_PEM=$(awk 'NF {printf "%s\\n", $0}' "$TMP_PRIV")
  JWT_PUBLIC_KEY_PEM=$(awk  'NF {printf "%s\\n", $0}' "$TMP_PUB")
  rm -f "$TMP_PRIV" "$TMP_PUB"
  ok "RS256 keypair generated"

  # Write .env
  step "Writing .env"
  cat > "$ENV_FILE" <<EOF
# Generated by deploy/install/install.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Keep this file private: chmod 600 .env

# ---- Postgres ----
POSTGRES_USER=drishtiai
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=drishtiai
DATABASE_URL=postgresql+psycopg://drishtiai:${POSTGRES_PASSWORD}@postgres:5432/drishtiai

# ---- Django ----
DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
DJANGO_DEBUG=false
ALLOWED_HOSTS=localhost,127.0.0.1

# ---- FastAPI ----
API_SECRET_KEY=${API_SECRET_KEY}
API_CORS_ORIGINS=http://localhost:3000

# ---- Redis ----
REDIS_URL=redis://redis:6379/0

# ---- MinIO ----
MINIO_ROOT_USER=drishtiai
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_ENDPOINT=minio:9000
MINIO_ACCESS_KEY=drishtiai
MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
MINIO_SECURE=false
MINIO_PRESIGNED_TTL_SECONDS=900

# ---- JWT (RS256) ----
JWT_PRIVATE_KEY_PEM=${JWT_PRIVATE_KEY_PEM}
JWT_PUBLIC_KEY_PEM=${JWT_PUBLIC_KEY_PEM}
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=15
JWT_REFRESH_TOKEN_EXPIRE_DAYS=7

# ---- Next.js ----
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_WS_URL=ws://localhost:8000

# ---- Pipeline ----
PIPELINE_GPU_ID=0
PIPELINE_LOG_LEVEL=INFO
PIPELINE_CAMERA_IDS=all
PIPELINE_FRAME_SAMPLE=5
PIPELINE_DEDUP_SECONDS=5
PIPELINE_VOTER_WINDOW_S=4.0
PIPELINE_VOTER_EXIT_GAP_S=1.5
PIPELINE_VOTER_MIN_READS=2
PIPELINE_CAPTURE_BACKEND=gstreamer
PIPELINE_OCR_USE_GPU=false
PIPELINE_OCR_TWO_STAGE=true
PIPELINE_OCR_PREPROCESS=true
PIPELINE_MIN_CONFIDENCE=0.40
PIPELINE_REVIEW_QUEUE_ENABLED=true

# ---- Seeding ----
SUPERADMIN_EMAIL=admin@drishtiai.local
SUPERADMIN_PASSWORD=${SUPERADMIN_PASSWORD}
RTSP_URL=rtsp://mediamtx:8554/test

# ---- Site ----
SITE_NAME=DrishtiAI Installation
SITE_TIMEZONE=Asia/Kathmandu

# ---- Gate credentials encryption ----
GATE_CREDENTIAL_KEY=${GATE_CREDENTIAL_KEY}

# ---- Observability ----
GRAFANA_PASSWORD=${GRAFANA_PASSWORD}
EOF
  chmod 600 "$ENV_FILE"
  ok ".env written (chmod 600)"
fi

# Source the env for use below
set -a; source "$ENV_FILE"; set +a

# ── 4. Install dependencies ───────────────────────────────────────────────────
step "Installing Python + JS dependencies"
cd "$REPO_ROOT"
uv sync --all-packages --quiet
pnpm install --frozen-lockfile --silent
ok "Dependencies installed"

# ── 5. Build Docker images ────────────────────────────────────────────────────
step "Building Docker images (this may take a few minutes)"
$COMPOSE build --quiet
ok "Images built"

# ── 6. Start infrastructure ───────────────────────────────────────────────────
step "Starting infrastructure services (postgres, redis, minio)"
$COMPOSE up -d postgres redis minio
echo "Waiting for Postgres to be ready..."
for i in $(seq 1 30); do
  $COMPOSE exec -T postgres pg_isready -U drishtiai -q 2>/dev/null && break
  sleep 2
done
$COMPOSE exec -T postgres pg_isready -U drishtiai -q || die "Postgres did not become ready"
ok "Infrastructure ready"

# ── 7. Migrations ─────────────────────────────────────────────────────────────
step "Running database migrations"
cd "$REPO_ROOT/packages/shared-python"
uv run alembic upgrade head
cd "$REPO_ROOT"
ok "Migrations complete"

# ── 8. Seed superadmin ────────────────────────────────────────────────────────
step "Seeding superadmin account"
uv run python apps/api/scripts/seed_superadmin.py
ok "Superadmin seeded"

# ── 9. Start full stack ───────────────────────────────────────────────────────
step "Starting full stack"
$COMPOSE up -d
ok "All services started"

# ── 10. Credential summary ────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  DrishtiAI installation complete${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  Dashboard        ${CYAN}http://localhost:3000${NC}"
echo -e "  API docs         ${CYAN}http://localhost:8000/api/docs${NC}"
echo -e "  Django admin     ${CYAN}http://localhost:8001/admin${NC}"
echo -e "  Grafana          ${CYAN}http://localhost:3001${NC}"
echo ""
echo -e "  Admin login:     ${CYAN}${SUPERADMIN_EMAIL:-admin@drishtiai.local}${NC}"
echo -e "  Admin password:  ${CYAN}${SUPERADMIN_PASSWORD:-<see .env>}${NC}"
echo -e "  Grafana login:   ${CYAN}admin / ${GRAFANA_PASSWORD:-<see .env>}${NC}"
echo ""
echo -e "  ${YELLOW}Credentials saved to: $ENV_FILE (chmod 600)${NC}"
echo -e "  ${YELLOW}Back it up securely — it cannot be regenerated.${NC}"
echo ""
echo -e "  To stop:  docker compose -f deploy/compose/docker-compose.yml down"
echo -e "  To start: docker compose -f deploy/compose/docker-compose.yml up -d"
echo ""
